# Generated by Django 5.0.3 on 2024-03-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Student first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Student last name')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='Student date of birth')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Student email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Student address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.person')),
                ('student_id', models.CharField(max_length=10, verbose_name='Student ID')),
            ],
            bases=('website.person',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100, verbose_name='Course code')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course name')),
                ('credits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of credits')),
                ('students', models.ManyToManyField(related_name='courses', to='website.student')),
            ],
        ),
    ]
